# Generated by Django 4.1.5 on 2023-03-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_pagefollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='you_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
