# Generated by Django 4.1.3 on 2023-03-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_facebook_link_user_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
