# Generated by Django 4.1.3 on 2023-03-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
    ]
