# Generated by Django 4.1.3 on 2023-03-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='offer_price',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
