# Generated by Django 4.1.3 on 2023-03-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_post_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
