# Generated by Django 4.1.3 on 2023-03-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_user_city_alter_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
