# Generated by Django 4.1.3 on 2023-03-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
    ]
