# Generated by Django 4.1.3 on 2023-03-30 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_remove_user_city_remove_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
