# Generated by Django 4.1.3 on 2023-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_friend_request_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
