# Generated by Django 4.1.3 on 2023-03-31 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_level2_level3'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lev2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.level2'),
        ),
    ]
