# Generated by Django 4.1.3 on 2023-04-10 09:06

from django.db import migrations, models
import network.validators


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_remove_invite_request_stat_invite_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vedio',
        ),
        migrations.AddField(
            model_name='post',
            name='Offer_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Offer_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Offer_toggle',
            field=models.CharField(default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Product_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.FileField(blank=True, null=True, upload_to='posts/', validators=[network.validators.file_size]),
        ),
        migrations.AddField(
            model_name='post',
            name='Offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
