# Generated by Django 4.1.3 on 2023-04-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_remove_post_doc_remove_post_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='education',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.URLField(blank=True, null=True),
        ),
    ]
