# Generated by Django 4.1.3 on 2023-04-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_rename_review_reviewreply_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping_address',
            new_name='Orders',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='quanty',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='user',
        ),
    ]
