# Generated by Django 4.1.3 on 2023-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_remove_order_create_at_remove_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='quanty',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Area',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='Full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='House',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='Landmark',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='Phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='State',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='Town',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='Zip',
            field=models.IntegerField(),
        ),
    ]
