# Generated by Django 4.1.3 on 2023-04-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_order_item_quanty_alter_order_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='price',
        ),
        migrations.AlterField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.post'),
        ),
    ]
