# Generated by Django 4.1.3 on 2023-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_remove_order_item_price_alter_order_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Area',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='House',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Landmark',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='State',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Town',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
