# Generated by Django 4.1.3 on 2023-04-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0039_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='average_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
