# Generated by Django 4.1.3 on 2023-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0040_alter_post_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('converted_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
