# Generated by Django 4.1.3 on 2023-04-21 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0041_currencyconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconversion',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
