# Generated by Django 4.1.3 on 2023-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0042_currencyconversion_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
