# Generated by Django 4.1.3 on 2023-04-24 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0044_remove_post_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite_request',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invite_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('User_Pending', 'User_Pending'), ('Joined', 'Joined'), ('Rejected', 'Rejected')], default='Pending', max_length=150),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Default', 'Default'), ('User_Fllow', 'User_Fllow'), ('User_Fllowing', 'User_Fllowing'), ('User_Post_like', 'User_Post_like'), ('User_Post_Reviwes', 'User_Post_Reviwes'), ('Page_Invitions_To_User', 'Page_Invitions_To_User'), ('User_Accept_Page_Invitions', 'User_Accept_Page_Invitions'), ('User_Page_Join_Request', 'User_Page_Join_Request'), ('Page_Accept_User_Invitions', 'Page_Accept_User_Invitions'), ('Page_Post_like', 'User_Post_like'), ('Page_Post_Reviwes', 'User_Post_Reviwes')], default='Default', max_length=150)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request', to='network.friend_request')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fr_noti', to=settings.AUTH_USER_MODEL)),
                ('invite_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_request', to='network.invite_request')),
                ('pages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagz_noti', to='network.page')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_noti', to='network.post')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_noti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
