# Generated by Django 4.1.3 on 2023-04-24 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0047_order_item_free_download_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
