# Generated by Django 4.1.3 on 2023-04-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0049_alter_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=True),
        ),
    ]
