# Generated by Django 4.1.3 on 2023-04-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0051_alter_post_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_viewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_viewed', to='network.post')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
