# Generated by Django 4.1.3 on 2023-04-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0052_post_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
