# Generated by Django 4.1.3 on 2023-04-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0053_remove_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
