# Generated by Django 4.1.3 on 2023-04-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0055_orderz_order_item_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Item',
        ),
    ]
