# Generated by Django 4.1.3 on 2023-04-25 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0057_order_itemz'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderz',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
