# Generated by Django 4.2 on 2023-05-02 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0059_notifications_reviewreply_notifications_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('Default', 'Default'), ('User_Fllow', 'User_Fllow'), ('User_Fllowing', 'User_Fllowing'), ('User_Post_like', 'User_Post_like'), ('User_New_Post', 'User_New_Post'), ('User_Post_Reviwes', 'User_Post_Reviwes'), ('User_Post_Reviwes_Replay', 'User_Post_Reviwes_Replay'), ('Page_Invitions_To_User', 'Page_Invitions_To_User'), ('User_Accept_Page_Invitions', 'User_Accept_Page_Invitions'), ('User_Page_Join_Request', 'User_Page_Join_Request'), ('Page_Accept_User_Invitions', 'Page_Accept_User_Invitions'), ('Page_New_Post', 'Page_New_Post'), ('Page_Post_like', 'User_Post_like'), ('Page_Post_Reviwes', 'Page_Post_Reviwes'), ('Page_Post_Reviwes_Replay', 'Page_Post_Reviwes_Replay'), ('Intrest_Post_Reviwes', 'Intrest_Post_Reviwes'), ('Intrest_Post_Reviwes_Replay', 'Intrest_Post_Reviwes_Replay'), ('Intrest_level_2_Post_Reviwes', 'Intrest_level_2_Post_Reviwes'), ('Intrest_level_2_Post_Reviwes_Replay', 'Intrest_level_2_Post_Reviwes_Replay')], default='Default', max_length=150),
        ),
        migrations.CreateModel(
            name='PostViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
