# Generated by Django 4.2 on 2023-05-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0060_alter_notifications_type_postviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
