# Generated by Django 4.1.3 on 2023-05-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0061_notifications_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
