# Generated by Django 4.1.3 on 2023-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0062_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrest',
            name='PARENT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
