# Generated by Django 4.1.3 on 2023-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0063_intrest_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intrest',
            old_name='PARENT',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='intrest',
            name='tooltip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
