# Generated by Django 4.1.3 on 2023-05-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0064_rename_parent_intrest_parent_intrest_tooltip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrest',
            name='tooltip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.intrest'),
        ),
    ]
