# Generated by Django 4.1.3 on 2023-05-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0065_alter_intrest_tooltip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrest',
            name='tooltip',
        ),
    ]
