# Generated by Django 4.1.3 on 2023-05-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0068_alter_intrest_parent_alter_intrest_tooltip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrest',
            name='tooltip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='network.intrest'),
        ),
    ]
