# Generated by Django 4.1.3 on 2023-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0069_alter_intrest_tooltip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrest',
            name='tooltip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
