# Generated by Django 4.1.3 on 2023-05-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0070_alter_intrest_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrest',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
