# Generated by Django 4.1.3 on 2023-05-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0071_intrest_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrest',
            name='tooltip2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
